#!/usr/bin/env bash
# Allocate an isolated LocalStack instance for this worktree and start it.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck disable=SC1091
source "${SCRIPT_DIR}/lib/localstack.sh"
# shellcheck disable=SC1091
source "${SCRIPT_DIR}/lib/prereqs.sh"

cd "${REPO_ROOT}"

require_docker

# Dummy credentials for LocalStack (aws CLI / SDKs). Matches infra/variables.tf defaults.
write_aws_env_lines() {
  cat <<EOF
# Dummy credentials for LocalStack (aws CLI / SDKs); not real AWS.
AWS_ACCESS_KEY_ID=test
AWS_SECRET_ACCESS_KEY=test
AWS_DEFAULT_REGION=us-east-1
AWS_REGION=us-east-1
AWS_ENDPOINT_URL=${LOCALSTACK_ENDPOINT}
EOF
}

ensure_aws_env() {
  # Drop prior AWS_* block (if any), then append the canonical one.
  if [[ -f "${LOCALSTACK_ENV_FILE}" ]]; then
    local tmp
    tmp="$(mktemp)"
    grep -Ev '^(# Dummy credentials for LocalStack|AWS_ACCESS_KEY_ID=|AWS_SECRET_ACCESS_KEY=|AWS_DEFAULT_REGION=|AWS_REGION=|AWS_ENDPOINT_URL=)' \
      "${LOCALSTACK_ENV_FILE}" >"${tmp}" || true
    mv "${tmp}" "${LOCALSTACK_ENV_FILE}"
  fi
  write_aws_env_lines >>"${LOCALSTACK_ENV_FILE}"
}

if [[ -f "${LOCALSTACK_ENV_FILE}" ]]; then
  load_localstack_env
  if ! docker_names="$(docker ps --format '{{.Names}}' 2>/dev/null)"; then
    echo "error: cannot talk to Docker (is the daemon running?)" >&2
    exit 1
  fi
  if grep -qx "${LOCALSTACK_DOCKER_NAME:-}" <<<"${docker_names}"; then
    ensure_aws_env
    load_localstack_env
    echo "LocalStack already running for this worktree."
    echo "  project:  ${COMPOSE_PROJECT_NAME}"
    echo "  name:     ${LOCALSTACK_DOCKER_NAME}"
    echo "  endpoint: ${LOCALSTACK_ENDPOINT}"
    echo "  env file: ${LOCALSTACK_ENV_FILE}"
    echo "  Next:     just package && just apply && just outputs"
    exit 0
  fi
  echo "Found stale ${LOCALSTACK_ENV_FILE}; recreating instance."
  "${SCRIPT_DIR}/localstack-down.sh" >/dev/null
fi

INSTANCE_ID="$(python3 -c 'import secrets; print(secrets.token_hex(4))')"
COMPOSE_PROJECT_NAME="thumbnail-${INSTANCE_ID}"
LOCALSTACK_DOCKER_NAME="localstack-${INSTANCE_ID}"
LOCALSTACK_VOLUME_DIR="${REPO_ROOT}/.localstack-${INSTANCE_ID}"
LOCALSTACK_EDGE_PORT="$(find_free_port 4566 4576 4586 4596)"
LOCALSTACK_EXTERNAL_HOST_START="$(find_free_port_range)"
LOCALSTACK_EXTERNAL_HOST_END="$((LOCALSTACK_EXTERNAL_HOST_START + EXTERNAL_PORT_WIDTH - 1))"
LOCALSTACK_ENDPOINT="http://127.0.0.1:${LOCALSTACK_EDGE_PORT}"

# Ensure the chosen edge port is not inside the external host range we just picked.
if (( LOCALSTACK_EDGE_PORT >= LOCALSTACK_EXTERNAL_HOST_START && LOCALSTACK_EDGE_PORT <= LOCALSTACK_EXTERNAL_HOST_END )); then
  LOCALSTACK_EDGE_PORT="$(find_free_port $((LOCALSTACK_EXTERNAL_HOST_END + 1)) $((LOCALSTACK_EXTERNAL_HOST_END + 11)))"
  LOCALSTACK_ENDPOINT="http://127.0.0.1:${LOCALSTACK_EDGE_PORT}"
fi

umask 077
cat > "${LOCALSTACK_ENV_FILE}" <<EOF
# Auto-generated by scripts/localstack-up.sh — do not commit.
# One isolated LocalStack instance for this worktree.
INSTANCE_ID=${INSTANCE_ID}
COMPOSE_PROJECT_NAME=${COMPOSE_PROJECT_NAME}
LOCALSTACK_DOCKER_NAME=${LOCALSTACK_DOCKER_NAME}
LOCALSTACK_VOLUME_DIR=${LOCALSTACK_VOLUME_DIR}
LOCALSTACK_EDGE_PORT=${LOCALSTACK_EDGE_PORT}
LOCALSTACK_EXTERNAL_HOST_START=${LOCALSTACK_EXTERNAL_HOST_START}
LOCALSTACK_EXTERNAL_HOST_END=${LOCALSTACK_EXTERNAL_HOST_END}
LOCALSTACK_ENDPOINT=${LOCALSTACK_ENDPOINT}
EOF
write_aws_env_lines >>"${LOCALSTACK_ENV_FILE}"

mkdir -p "${LOCALSTACK_VOLUME_DIR}"

echo "Starting LocalStack (${COMPOSE_PROJECT_NAME}) on ${LOCALSTACK_ENDPOINT} ..."
compose up -d

echo "Waiting for health ..."
ready=0
for _ in $(seq 1 60); do
  if curl -sf "${LOCALSTACK_ENDPOINT}/_localstack/health" >/dev/null; then
    ready=1
    break
  fi
  sleep 1
done

if [[ "${ready}" -ne 1 ]]; then
  echo "error: LocalStack did not become healthy at ${LOCALSTACK_ENDPOINT}" >&2
  compose ps >&2 || true
  exit 1
fi

echo "LocalStack ready."
echo "  project:  ${COMPOSE_PROJECT_NAME}"
echo "  name:     ${LOCALSTACK_DOCKER_NAME}"
echo "  endpoint: ${LOCALSTACK_ENDPOINT}"
echo "  env file: ${LOCALSTACK_ENV_FILE}"
echo
echo "Next: just package && just apply && just outputs"
echo "  (or: just deploy)"
echo
echo "Shell tip: set -a && source .localstack.env && set +a"
